name: NodeCiCD

on: 
  push:
    branches: [main]
    paths:
      - 'nodejs/**'
      - '.github/workflows/node_ci_cd.yml'
  pull_request:
    paths:
      - 'nodejs/**'

jobs:
  test-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodejs
    steps:
      - name: cache node modules
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('nodejs/package-lock.json') }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  deploy:
    needs: test-node
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: nodejs/public
      - id: deployment
        uses: actions/deploy-pages@v3
        
      
  