name: PythonCiCD

on:
  push:
    branches: [main]
    paths:
      - 'python/**'
      - '.github/workflows/python_ci_cd.yml'
  pull_request:
    paths:
      - 'python/**'

jobs:
  test-python:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python
    steps:
      - name: cache pip
        uses: actions/cache@v6
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('python/requirements.txt') }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with pylint
        run: pylint *.py

      - name: Run tests
        run: pytest
